services:
  postgres:
    # versioin:12-alpineを使用(alphinはサイズが小さいらしい)
    image: postgres:12-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=mydb
    # データの永続化
    volumes:
      # DB情報は/var/lib/postgresql/dataに保存されるが、永続化のためpostgresディレクトリを/var/lib/postgresql/dataにマウント
      - postgres:/var/lib/postgresql/data
    # ポートの指定（HOST:CONTAINER）
    ports:
      - 5432:5432
# データの永続化
volumes:
  postgres:
